# NestJS API Application
# Aplicação principal da API com health checks robustos

apiVersion: v1
kind: ConfigMap
metadata:
  name: nestjs-api-config
  namespace: boyscout
  labels:
    app.kubernetes.io/name: nestjs-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: boyscout
data:
  NODE_ENV: "production"
  PORT: "3000"
  SERVICE_NAME: "nestjs-api"
  SERVICE_VERSION: "1.0.0"
  DATABASE_URL: "postgres://boyscout:boyscout123@postgresql:5432/boyscout?sslmode=disable"
  REDIS_URL: "redis://redis:6379"
  KEYCLOAK_URL: "http://keycloak:80"
  KEYCLOAK_REALM: "boyscout"
  RABBITMQ_URL: "amqp://boyscout:boyscout123@rabbitmq:5672/boyscout"

---
apiVersion: v1
kind: Secret
metadata:
  name: nestjs-api-secret
  namespace: boyscout
  labels:
    app.kubernetes.io/name: nestjs-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: boyscout
type: Opaque
data:
  # Base64 encoded secrets (example values)
  JWT_SECRET: Ym95c2NvdXRfam10X3NlY3JldA==
  API_KEY: Ym95c2NvdXRfYXBpX2tleQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-api
  namespace: boyscout
  labels:
    app.kubernetes.io/name: nestjs-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: boyscout
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nestjs-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nestjs-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: boyscout
    spec:
      containers:
      - name: nestjs-api
        image: boyscout/nestjs-api:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nestjs-api-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: nestjs-api-config
              key: PORT
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: nestjs-api-config
              key: SERVICE_NAME
        - name: SERVICE_VERSION
          valueFrom:
            configMapKeyRef:
              name: nestjs-api-config
              key: SERVICE_VERSION
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: nestjs-api-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: nestjs-api-config
              key: REDIS_URL
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: nestjs-api-config
              key: KEYCLOAK_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: nestjs-api-config
              key: KEYCLOAK_REALM
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: nestjs-api-config
              key: RABBITMQ_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nestjs-api-secret
              key: JWT_SECRET
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: nestjs-api-secret
              key: API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 12
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-api
  namespace: boyscout
  labels:
    app.kubernetes.io/name: nestjs-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: boyscout
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: nestjs-api

---
# HorizontalPodAutoscaler para escalonamento automático
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nestjs-api-hpa
  namespace: boyscout
  labels:
    app.kubernetes.io/name: nestjs-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: boyscout
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nestjs-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
